"""Helpers for Hong Kong's Security of Payment Ordinance (Cap. 652).

Cap. 652 (the Construction Industry Security of Payment Ordinance) came into
force for new construction contracts from 28 Aug 2025. It gives contractors
and subcontractors a statutory right to progress payments, a right to a
payment response, and a fast adjudication route for payment disputes.

This module is a small, deterministic helper for a demo app. It covers three
things:

  1. A statutory deadline engine (payment response, payment due date,
     adjudication referral window) computed from a single claim date.
  2. Payment claim and payment response document generators that fill in the
     mandatory content Cap. 652 expects (in writing, identifies the work,
     states the amount, gives the basis of calculation).
  3. A clause auditor that flags pay-when-paid / conditional-payment language
     in uploaded contract text, which Cap. 652 bans in construction contracts.

Nothing here is legal advice. The section numbers below are the ones most
commonly cited for each default period, but the Ordinance, the contract, and
the facts of any real dispute all matter. This is a screening aid, not a
substitute for a lawyer or a QS.
"""

import re
from datetime import date, datetime, timedelta

# Default statutory periods, in days. These are the general defaults under
# Cap. 652; individual contracts may extend some of them within statutory
# limits. Kept as named constants so the source of each number is visible.
RESPONSE_DAYS = 30      # s. 31: payment response due within 30 days of the claim
PAYMENT_DAYS = 60       # s. 32: payment due date, default 60 days after the claim
ADJUDICATION_DAYS = 28  # s. 47/48: payment dispute referral window, 28 days


def _as_date(value):
    """Coerce a date, datetime, or ISO 'YYYY-MM-DD' string into a date."""
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    return date.fromisoformat(str(value))


def _money(x):
    """Format a numeric amount as a Hong Kong dollar string."""
    return f"HK${float(x or 0):,.2f}"


def deadlines(claim_date):
    """Compute the statutory payment timetable from a payment claim date.

    Given the date a payment claim is served, return a dict with:

      claim_date                 the claim date itself (a datetime.date)
      payment_response_deadline  claim_date + 30 days (Cap. 652 s. 31 default)
      payment_deadline           claim_date + 60 days (Cap. 652 s. 32 default)
      adjudication_window_open   the payment deadline (a payment dispute is
                                 treated here as arising when payment falls due)
      adjudication_window_close  adjudication_window_open + 28 days
                                 (Cap. 652 s. 47/48 referral window)

    Dates are plain Python dates (no timezone object is needed for day
    arithmetic); Hong Kong time is only a display concern. If a payment
    dispute in fact arises earlier, for example on receipt of an inadequate
    payment response, the 28-day referral clock may start earlier than the
    default anchor used here. Verify against the contract and the Ordinance.
    """
    claim = _as_date(claim_date)
    response = claim + timedelta(days=RESPONSE_DAYS)
    due = claim + timedelta(days=PAYMENT_DAYS)
    adjudication_open = due
    adjudication_close = due + timedelta(days=ADJUDICATION_DAYS)
    return {
        "claim_date": claim,
        "payment_response_deadline": response,
        "payment_deadline": due,
        "adjudication_window_open": adjudication_open,
        "adjudication_window_close": adjudication_close,
    }


def format_hk(d):
    """Render a date for display in Hong Kong time (ISO date, labelled HKT)."""
    d = _as_date(d)
    return f"{d.isoformat()} (HKT)"


def deadline_summary(info):
    """Plain-language summary of a deadline dict from deadlines()."""
    return (
        f"Payment claim served {format_hk(info['claim_date'])}. "
        f"Payment response due {format_hk(info['payment_response_deadline'])}. "
        f"Payment due {format_hk(info['payment_deadline'])}. "
        f"Adjudication referral window opens {format_hk(info['adjudication_window_open'])} "
        f"and closes {format_hk(info['adjudication_window_close'])}."
    )


NOT_LEGAL_ADVICE = (
    "This document was generated by a screening helper and is not legal advice. "
    "Review it against Cap. 652 and the contract before serving it."
)


def _build_document(kind, title, clauses):
    """Shared renderer: number clauses and join them into plain text."""
    numbered = []
    for i, (heading, body) in enumerate(clauses, start=1):
        numbered.append({"no": i, "heading": heading, "text": body})
    sections = [{"heading": title, "clauses": numbered}]
    lines = [title, "=" * len(title)]
    for c in numbered:
        lines.append(f"{c['no']}. {c['heading']}")
        lines.append(f"   {c['text']}")
    lines.append("")
    lines.append(NOT_LEGAL_ADVICE)
    return {
        "kind": kind,
        "title": title,
        "clauses": numbered,
        "sections": sections,
        "text": "\n".join(lines),
    }


def payment_claim(info):
    """Build a structured payment claim from a dict of claim details.

    Cap. 652 requires a payment claim to be in writing, to identify the
    construction work to which it relates, and to state the amount claimed
    and the basis on which it is calculated (s. 29). This generator turns the
    supplied details into numbered clauses that carry each of those elements.

    Expected keys in `info`:
      work_period          the period the claim covers (e.g. "1-31 Aug 2026")
      work_description     what work was done
      amount_claimed       the claimed amount (numeric)
      basis_of_calculation optional; how the amount was worked out, or a
                           breakdown line list under 'breakdown'
      claimant, respondent, contract_ref, claim_number  optional identifiers

    Returns a dict with 'text' (plain text with numbered clauses), 'sections',
    'clauses', and 'mandatory' (the Cap. 652 elements the document covers).
    """
    amount = info.get("amount_claimed")
    clauses = [
        ("Parties", (
            f"This payment claim is served by {info.get('claimant', 'the claimant')} "
            f"on {info.get('respondent', 'the respondent')}"
            + (f" under {info.get('contract_ref')}." if info.get("contract_ref") else ".")
        )),
        ("Claim number", (
            f"Payment claim no. {info.get('claim_number', '(un-numbered)')}."
        )),
        ("Work period", (
            f"This claim covers work carried out during {info.get('work_period', '(period not stated)')}."
        )),
        ("Work done", (
            f"{info.get('work_description', '(no work description supplied)')}."
        )),
        ("Amount claimed", (
            f"The amount claimed is {_money(amount)}."
        )),
        ("Basis of calculation", (
            info.get("basis_of_calculation")
            or "(no basis of calculation supplied; Cap. 652 requires the claim to state how the amount was calculated)"
        )),
    ]
    doc = _build_document("payment_claim", "Payment Claim", clauses)
    doc["amount_claimed"] = amount
    doc["work_description"] = info.get("work_description")
    doc["mandatory"] = ["in_writing", "identifies_work", "states_amount", "basis_of_calculation"]
    return doc


def payment_response(info):
    """Build a structured payment response from a dict of response details.

    Cap. 652 requires the respondent to a payment claim to respond in writing,
    stating the amount it proposes to pay (the admitted amount), any amount
    withheld or disputed, and the reasons for the difference, with the basis
    of calculation for the admitted amount. This generator separates the
    admitted amount from the disputed amount so the two never blur together.

    Expected keys in `info`:
      work_period, work_description  context of the claim being answered
      amount_claimed                 the original claimed amount
      admitted_amount                amount the respondent proposes to pay
      disputed_amount                amount withheld / disputed
      reasons                        why the remainder is disputed
      calculation                    basis of calculation for the admitted amount
      claimant, respondent, contract_ref, claim_number  optional identifiers

    Returns the same shape as payment_claim().
    """
    claimed = info.get("amount_claimed")
    admitted = info.get("admitted_amount")
    disputed = info.get("disputed_amount", (claimed or 0) - (admitted or 0))
    clauses = [
        ("Parties", (
            f"This payment response is given by {info.get('respondent', 'the respondent')} "
            f"to {info.get('claimant', 'the claimant')}"
            + (f" under {info.get('contract_ref')}." if info.get("contract_ref") else ".")
        )),
        ("Claim answered", (
            f"Responding to payment claim no. {info.get('claim_number', '(un-numbered)')} "
            f"for work during {info.get('work_period', '(period not stated)')}."
        )),
        ("Admitted amount", (
            f"The respondent proposes to pay {_money(admitted)}."
        )),
        ("Disputed amount", (
            f"The respondent withholds {_money(disputed)} "
            f"of the claimed {_money(claimed)}."
        )),
        ("Reasons for the difference", (
            info.get("reasons") or "(no reasons supplied; Cap. 652 requires reasons for any amount withheld)"
        )),
        ("Basis of calculation", (
            info.get("calculation") or "(no basis of calculation supplied for the admitted amount)"
        )),
    ]
    doc = _build_document("payment_response", "Payment Response", clauses)
    doc["admitted_amount"] = admitted
    doc["disputed_amount"] = disputed
    doc["amount_claimed"] = claimed
    return doc


# Pay-when-paid / conditional-payment language. Cap. 652 voids provisions that
# make a party's obligation to pay conditional on that party first being paid
# by a third party. Each entry pairs a regex with a short human label. English
# phrases allow flexible whitespace; Chinese phrases are matched literally.
CLAUSE_PATTERNS = [
    (r"pay\s+when\s+paid", "pay when paid"),
    (r"pay\s+when\s+certified", "pay when certified"),
    (r"conditional\s+payment", "conditional payment"),
    (r"no\s+payment\s+until", "no payment until"),
    (r"back\s*[- ]?\s*to\s*[- ]?\s*back", "back to back"),
    (r"if\s+and\s+only\s+if\s+(?:we\s+)?receive\s+payment", "if and only if we receive payment"),
    (r"upon\s+receipt\s+of\s+payment", "upon receipt of payment"),
    (r"subject\s+to\s+receipt\s+of\s+payment", "subject to receipt of payment"),
    (r"以收到付款為條件", "conditional on receiving payment"),
    (r"收妥款項後才付款", "pay only after receipt of payment"),
    (r"收到付款後才付款", "pay after receipt of payment"),
    (r"有條件付款", "conditional payment"),
]

_COMPILED = [(re.compile(p, re.IGNORECASE), label) for p, label in CLAUSE_PATTERNS]

_EXCERPT_WINDOW = 40


def _excerpt(text, start, end):
    """A short quoted slice around a match for a flag's evidence field."""
    lo = max(0, start - _EXCERPT_WINDOW)
    hi = min(len(text), end + _EXCERPT_WINDOW)
    prefix = "..." if lo > 0 else ""
    suffix = "..." if hi < len(text) else ""
    snippet = re.sub(r"\s+", " ", text[lo:hi]).strip()
    return f"{prefix}{snippet}{suffix}"


def scan_contract(text):
    """Flag pay-when-paid / conditional-payment clauses in contract text.

    Cap. 652 bans provisions that make payment to a party conditional on that
    party being paid by someone else (a so-called pay-when-paid clause). This
    is a pure regex/keyword screen over the text; it does not understand legal
    nuance and may miss reworded clauses or flag benign mentions. Every hit is
    marked 'critical' so it is surfaced for a human to read in context.

    Returns a list of dicts: severity, description, detail, excerpt. An empty
    list means no matched pattern was found, not that the contract is clean.
    """
    text = text or ""
    flags = []
    seen = set()
    for pattern, label in _COMPILED:
        for m in pattern.finditer(text):
            start, end = m.start(), m.end()
            key = (label, start, end)
            if key in seen:
                continue
            seen.add(key)
            flags.append({
                "severity": "critical",
                "description": f'Possible pay-when-paid clause: "{label}"',
                "detail": (
                    "Cap. 652 voids provisions that make payment conditional on "
                    "receiving payment from a third party. Read the clause in full "
                    "and confirm with legal advice before relying on it."
                ),
                "excerpt": _excerpt(text, start, end),
            })
    return flags


def scan_summary(flags):
    """One-line summary of clause audit results."""
    if not flags:
        return "No pay-when-paid language matched. Read the full contract to be sure."
    return f"{len(flags)} possible pay-when-paid clause(s) flagged for review."
